### ISSUE TITLE
What's data update story?

### ISSUE THREAD

**Issue by julianrz** [bluestreak01/questdb#57]
I found that /imp does not overwrite or append existing data, at least judging by web console results.   A new table can be created with new data, but this is not practical in most cases. Is there an update story in this DB, or is this meant to be a load/analyze/drop thing?

**Comment by bluestreak01** [comment]
By default `/imp` appends and overwrites with `overwrite=true` query parameter if you are uploading from outside of web console. I put together a description here: 

https://doc.questdb.org/#doc-api-rest-dataload-intro 

Web console give you an option to append or overwrite if table exists when you click on "failed" import row:

<img width="1437" alt="screen shot 2016-12-30 at 09 54 54" src="https://cloud.githubusercontent.com/assets/7276403/21562163/b08d38f2-ce76-11e6-9fb0-37e332ebc31f.png">

**Comment by julianrz** [comment]
So if overwrite=false, by default, it is supposed to ignore all input, including records that are not in current table? I expected it to append...

**Comment by bluestreak01** [comment]
it should append, yes. What version are you on and what happens when you omit "overwrite" parameter?

**Comment by julianrz** [comment]
1.0.2, this is what brew installs. When I omit overwrite, no change to the table occurs, unless this is a new table

**Comment by bluestreak01** [comment]
I can confirm it is a bug in 1.0.2. It'll be fixed tomorrow. There is no concept of key, but there is concept of many versions of the same entity and a way of selecting latest version. Example is to follow asap

**Comment by julianrz** [comment]
Vlad, thanks for fast response. Nothing critical, just playing with your stuff, if I can help make it better, great!I am not sure how versioning helps when you want to update a specific record. Normally I would select it by key and overwrite another field. How would I select a record to update it? Suppose I have a record containing field1=a, field2=b. I want to update it to contain field2=c. I want to say update where field1=a. Just appending another record field1=a, field2=c creates two unique records, not two versions of the same record? What identifies a record, if not key? i can see key working together with version, but version without key??-Julian 

    On Friday, December 30, 2016 1:27 PM, Vlad Ilyushchenko <notifications@github.com> wrote:
 

 I can confirm it is a bug in 1.0.2. It'll be fixed tomorrow. There is no concept of key, but there is concept of many versions of the same entity and a way of selecting latest version. Example is to follow asap—

**Comment by bluestreak01** [comment]
hey Julian, you got it right i think. I took your example and created a table upfront, before uploading:

`create table 'a.txt' (field1 symbol index, field2 string)`

Here `symbol` is column data type and `index` keyword creates index on the field. 
I then uploaded 'a.txt' that contained:

```
a,b
```

followed by same file containing
```
a,c
```

you are right, i get two rows:
<img width="1302" alt="screen shot 2016-12-31 at 15 26 27" src="https://cloud.githubusercontent.com/assets/7276403/21577939/b4d0fd66-cf6d-11e6-91f6-9e7b5ac519fe.png">

but because i have `field1` indexed i can now run this query:

`'a.txt' latest by field1`

What it tells questdb to do is to group all records on values of `field1` and get chronologically latest record for each value. The result is:

<img width="1305" alt="screen shot 2016-12-31 at 15 27 09" src="https://cloud.githubusercontent.com/assets/7276403/21577949/20ebeaa6-cf6e-11e6-99af-cc6859522ba6.png">

Questdb of course does not do brute force grouping etc. it uses index and will execute fast regardless of how many records with `field1=a` you have.

Hope this makes sense?

My working copy doesn't have this append bug, but then i fixed quite a lot of them! I'll create another brew package in a few mins and let you know.

**Comment by julianrz** [comment]
Hi Vlad,yes it does make sense, thanks for explaining... it is quite interesting and innovative, keep it up:)Happy New Year!Julian 

    On Saturday, December 31, 2016 6:34 AM, Vlad Ilyushchenko <notifications@github.com> wrote:
 

 hey Julian, you got it right i think. I took your example and created a table upfront, before uploading:create table 'a.txt' (field1 symbol index, field2 string)Here symbol is column data type and index keyword creates index on the field.
I then uploaded 'a.txt' that contained:a,b
followed by same file containinga,c
you are right, i get two rows:
but because i have field1 indexed i can now run this query:'a.txt' latest by field1What it tells questdb to do is to group all records on values of field1 and get chronologically latest record for each value. The result is:Questdb of course does not do brute force grouping etc. it uses index and will execute fast regardless of how many records with field1=a you have.Hope this makes sense?My working copy doesn't have this append bug, but then i fixed quite a lot of them! I'll create another brew package in a few mins and let you know.—

**Comment by bluestreak01** [comment]
Happy New Year Julian!

**Comment by bluestreak01** [comment]
Hi Julian,

I cut a new release `1.0.4`, which fixes append bug along with some others. You can install it via `brew upgrade questdb` and start with `questdb start -f`. `-f` flag will have questdb overwrite internal html page and scripts. Old ones are not compatible with new server.

**Comment by julianrz** [comment]
Hi Vlad, works now, I see record updated, and also can get latest by key. Very cool!

**Comment by bluestreak01** [comment]
Great! Be sure to let me know if I can help with anything.
